version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      QUEUE_NAME: my_queue
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
